name: 'WiNet Extractor'
description: 'Extracts data from WiNet devices and sends to Home Assistant over MQTT.'
version: '0.2.2'
stage: 'stable'
slug: 'winet-extractor'
url: 'https://github.com/renetrussellcullen-debug/home-assistant-repo.git'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
map:
  - config:rw
panel_icon: mdi:solar-power
auth_api: false
hassio_role: 'default'
hassio_api: false
homeassistant_api: false
startup: 'application'
init: false
services:
  - mqtt:need

options:
  winet_host: ''
  winet_port: ''
  mqtt_url: ''
  winet_user: ''
  winet_pass: ''
  poll_interval: 10
  analytics: true
  ssl: false

schema:
  winet_host: str
  winet_port: str
  mqtt_url: str
  winet_user: str?
  winet_pass: str?
  poll_interval: int(1,3600)
  analytics: bool
  ssl: bool
